<a href="https://colab.research.google.com/github/kararmirza19/kararmirza19/blob/main/Movies_Recommender__Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

data = pd.read_csv("/content/filmtv_movies.csv", encoding="utf-8", error_bad_lines=False)
data



<ipython-input-46-0af1bbddf2a5>:5: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  data = pd.read_csv("/content/filmtv_movies.csv", encoding="utf-8", error_bad_lines=False)
Skipping line 1338: expected 19 fields, saw 20



filmtv_id                                        title  year  \
0              2  Bugs Bunny's Third Movie: 1001 Rabbit Tales  1982   
1              3                    18 anni tra una settimana  1991   
2             17                             Ride a Wild Pony  1976   
3             18                                        Diner  1982   
4             20              A che servono questi quattrini?  1942   
...          ...                                          ...   ...   
36872     232817                           Gold Digger Killer  2021   
36873     232893                          Addio al nubilato 2  2023   
36874     232915                                  Konferensen  2023   
36875     232919                                    Ballelina  2023   
36876     232920                    Invitación a un Asesinato  2023   

           genre  duration                country  \
0      Animation        76          United States   
1          Drama        98                  Italy   
2       Romantic        91          United States   
3         Comedy        95          United States   
4         Comedy        85                  Italy   
...          ...       ...                    ...   
36872   Thriller        87  Canada, United States   
36873     Comedy        90                  Italy   
36874     Horror       100                 Sweden   
36875   Thriller        92            South Korea   
36876   Thriller        92                 Mexico   

                                  directors  \
0      David Detiege, Art Davis, Bill Perez   
1                             Luigi Perelli   
2                               Don Chaffey   
3                            Barry Levinson   
4                            Esodo Pratelli   
...                                     ...   
36872                            Robin Hays   
36873                    Francesco Apolloni   
36874                         Patrik Eklund   
36875                        Chung-Hyun Lee   
36876                          J.M Cravioto   

                                                  actors  avg_vote  \
0                                                    NaN       7.7   
1      Kim Rossi Stuart, Simona Cavallari, Ennio Fant...       6.5   
2      Michael Craig, John Meillon, Eva Griffith, Gra...       5.7   
3      Mickey Rourke, Steve Guttenberg, Ellen Barkin,...       7.0   
4      Eduardo De Filippo, Peppino De Filippo, Clelia...       5.9   
...                                                  ...       ...   
36872  Julie Benz, Roan Curtis, Georgia Bradner, Eli ...       4.0   
36873  Laura Chiatti, Chiara Francini, Antonia Liskov...       2.7   
36874  Katia Winter, Eva Melander, Lola Zackow, Adam ...       6.0   
36875             Jeon Jong-seo, Park Yu-rim, Ji-hun Kim       5.8   
36876  Maribel Verdú, Stephanie Cayo, Manolo Cardona,...       6.0   

       critics_vote  public_vote  total_votes  \
0              8.00          7.0           22   
1              6.00          7.0            4   
2              6.00          5.0           10   
3              8.00          6.0           18   
4              5.33          7.0           15   
...             ...          ...          ...   
36872           NaN          4.0            3   
36873           NaN          3.0            3   
36874           NaN          6.0            6   
36875           NaN          6.0            5   
36876           NaN          6.0            3   

                                             description  \
0      With two protruding front teeth, a slightly sl...   
1      Samantha, not yet eighteen, leaves the comfort...   
2      In the Australia of the pioneers, a boy and a ...   
3      Five boys from Baltimore have a habit of meeti...   
4      With a stratagem, the penniless and somewhat p...   
...                                                  ...   
36872  Celeste is an attractive waitress in the forti...   
36873  When Eleonora is downloaded to the 

In [ ]:
# Checking and handling missing values

data.isnull().sum()
data.dropna(inplace=True)

data

filmtv_id                                title  year     genre  \
1              3            18 anni tra una settimana  1991     Drama   
2             17                     Ride a Wild Pony  1976  Romantic   
3             18                                Diner  1982    Comedy   
4             20      A che servono questi quattrini?  1942    Comedy   
5             21               The Uranian Conspiracy  1978       Spy   
...          ...                                  ...   ...       ...   
36760     224974  Il fascino dell'insolito: Impostore  1981    Sci-Fi   
36769     225477                  She Is Me, I Am Her  2022     Drama   
36795     226388               The Exorcist: Believer  2023    Horror   
36798     226639                           Sambizanga  1972     Drama   
36824     229120                           The Nun II  2023    Horror   

       duration                       country  \
1            98                         Italy   
2            91                 United States   
3            95                 United States   
4            85                         Italy   
5           117        Italy, Germany, Israel   
...         ...                           ...   
36760        52                         Italy   
36769        70                         Japan   
36795       121                 United States   
36798        97                Angola, France   
36824       110  United States, Great Britain   

                                  directors  \
1                             Luigi Perelli   
2                               Don Chaffey   
3                            Barry Levinson   
4                            Esodo Pratelli   
5      Gianfranco Baldanello, Menahem Golan   
...                                     ...   
36760         Andrea Frazzi, Antonio Frazzi   
36769                         Mayu Nakamura   
36795                    David Gordon Green   
36798                        Sarah Maldoror   
36824                        Michael Chaves   

                                                  actors  avg_vote  \
1      Kim Rossi Stuart, Simona Cavallari, Ennio Fant...       6.5   
2      Michael Craig, John Meillon, Eva Griffith, Gra...       5.7   
3      Mickey Rourke, Steve Guttenberg, Ellen Barkin,...       7.0   
4      Eduardo De Filippo, Peppino De Filippo, Clelia...       5.9   
5      Fabio Testi, Janet Agren, Assaf Dayan, Siegfri...       4.8   
...                                                  ...       ...   
36760  Daniele Dublino, Adalberto Maria Merli, Antoni...       4.8   
36769  Nahana, Fusako Urabe, Kôta Kusano, Masao Yoshi...       6.5   
36795  Ellen Burstyn, Leslie Odom Jr., Ann Dowd, Raph...       4.1   
36798  Elisa Andrade, Jean M'Vondo, Dino Abelino, Ben...       7.5   
36824  Taissa Farmiga, Storm Reid, Anna Popplewell, B...       5.2   

       critics_vote  public_vote  total_votes  \
1              6.00          7.0            4   
2              6.00          5.0           10   
3              8.00          6.0           18   
4              5.33          7.0           15   
5              3.50          6.0            5   
...             ...          ...          ...   
36760          4.50          5.0            3   
36769          7.00          6.0            3   
36795          4.00          4.0           17   
36798          7.50          8.0            4   
36824          5.50          5.0           17   

                                             description  \
1      Samantha, not yet eighteen, leaves the comfort...   
2      In the Australia of the pioneers, a boy and a ...   
3      Five boys from Baltimore have a habit of meeti...   
4      With a stratagem, the penniless and somewhat p...   
5      Two Israeli secret agents discover that traffi...   
...                                                  ...   
36760  An alien spatial ship arrives on Earth and a c...   
36769  A phone call between three former friends of t...   
36795 

In [ ]:
#  Building the Recommendation System
# Create a feature matrix using CountVectorizer:
# Calculation of cosine similarity between movies:

vector = CountVectorizer()
features = vector.fit_transform(data["description"])
similarity_matrix = cosine_similarity(features)

print(similarity_matrix)

[[1.         0.58669926 0.36792475 ... 0.38323816 0.50789938 0.40470392]
 [0.58669926 1.         0.31525772 ... 0.47775452 0.56280925 0.4578    ]
 [0.36792475 0.31525772 1.         ... 0.2574121  0.29240925 0.21746411]
 ...
 [0.38323816 0.47775452 0.2574121  ... 1.         0.38112741 0.31887407]
 [0.50789938 0.56280925 0.29240925 ... 0.38112741 1.         0.46101675]
 [0.40470392 0.4578     0.21746411 ... 0.31887407 0.46101675 1.        ]]


In [ ]:

# Define a function to recommend movies based on a target movie:

def recommend_movies(movie_id, top_n=10):
    similar_movies = np.argsort(similarity_matrix[movie_id])[1:top_n+1]
    recommended_movies = data.iloc[similar_movies][["title", "year", "genre"]].values.tolist()
    return recommended_movies



In [ ]:
target_movie = data[data["title"] == "The Matrix"].index[0]

In [ ]:
#Displaying Top 10 Recommendations from the data set

recommendations = recommend_movies(target_movie)

print(f"Top 10 recommended movies for The Matrix:\n")
for i, movie in enumerate(recommendations, start=1):
    title, year, genre = movie
    print(f"{i}. {title} ({year})  Genre {genre}")


Top 10 recommended movies for The Matrix:

1. Der Dirnenmörder von London (1976)  Genre Drama
2. Taare Zameen Par  (2007)  Genre Drama
3. Ringo e Gringo contro tutti (1966)  Genre Comedy
4. Fair Play (2006)  Genre Thriller
5. Quattro bravi ragazzi (1993)  Genre Drama
6. Radio (2003)  Genre Drama
7. A ridosso dei ruderi, i Trionfi (1997)  Genre Sperimental
8. Papa Luciani. Il sorriso di Dio (2006)  Genre Drama
9. Hwajang (2014)  Genre Drama
10. Hanjo mugen jigoku (1970)  Genre Drama
